[manifest]
version = "1.0.0"
dump_lua = true
priority = 1



# Stop player from accessing level
# TODO: Do this instead of make deco?
[[patches]]
[patches.pattern]
target = "states/AtomMap.lua"
pattern = 'function st:selectLevel(quark)'
position = "after"
payload = '''
-- print(quark.level.id)
if ap.connected and atID ~= "IDMISSINGFUCK" and not ap.data.has_goal and false then
    local APIID = ap.data.atom_keys[atID]
    -- Check for Atom Key
    if not (ap.data.items[APIID]) then
        return
    end
end
'''
match_indent = true

# make deco
[[patches]]
[patches.pattern]
target = "states/AtomMap.lua"
pattern = '''local unlocked = true'''
position = "after"
payload = '''
local isDeco = false
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/AtomMap.lua"
pattern = '''obj = em.init(
			"LevelQuark",
			{ 
				level = self.basePath .. "/" .. objectData.level,
				path = objectData.level,
				atomLayer = layer + 1,
				unlockState = objectData.unlockState,
				saveName = UnlockManager.grabSaveName(objectData),
				variantUnlocks = objectData.variantUnlocks,
				hint = objectData.hint,
				noRing = objectData.noRing,
				bossLevel = objectData.boss,
				erachimaera = objectData.erachimaera,
				anomaly = objectData.anomaly
		 	}
		)'''
position = "at"
payload = '''
obj = em.init(
    "LevelQuark",
    { 
        DecoOnly = isDeco,
        level = self.basePath .. "/" .. objectData.level,
        path = objectData.level,
        atomLayer = layer + 1,
        unlockState = objectData.unlockState,
        saveName = UnlockManager.grabSaveName(objectData),
        variantUnlocks = objectData.variantUnlocks,
        hint = objectData.hint,
        noRing = objectData.noRing,
        bossLevel = objectData.boss,
        erachimaera = objectData.erachimaera,
        anomaly = objectData.anomaly
    }
)'''
match_indent = true

# Stop player from accessing level
[[patches]]
[patches.pattern]
target = "states/AtomMap.lua"
pattern = '''
	if objectData.unlockConditions then
		unlocked = UnlockManager.evalUnlocks(objectData, objectData.unlockConditions)
	end'''
position = "at"
payload = '''
if objectData.unlockConditions then
    unlocked = UnlockManager.evalUnlocks(objectData, objectData.unlockConditions)
    if ap.connected and not ap.data.has_goal then
        if objectData.type == "Level" then
            -- print("Level: " .. objectData.level)
            unlocked = false
            local metadata = dpf.loadJson("levels/" .. tostring(objectData.level) .. "/manifest.json").metadata
            for x,y in ipairs(ap.data.playable) do
                if (metadata.songName == y.name) then
                
                    -- Check if atom is unlocked
                    local APID = ap.data.atom_keys[ap.levels[metadata.songName].atom]
                    for x,y in ipairs(ap.data.received) do
                        AtomUnlocked = y == APID
                        unlocked = true
                        if AtomUnlocked then break end
                    end
                    
                    break
                end  
            end

            if not AtomUnlocked and unlocked then
                unlocked = false
                print(metadata.songName .. " isnt unlocked")
            end
        elseif objectData.type == "Atom" then
            unlocked = true
            objectData.unlockState = 2
        end
    end
else
    -- Nucleus dont have unlock conditions
    if ap.connected and not ap.data.has_goal then
        if objectData.type == "Level" then
            local metadata = dpf.loadJson("levels/" .. tostring(objectData.level) .. "/manifest.json").metadata
            for x,y in ipairs(ap.data.playable) do
                isDeco = not (metadata.songName == y.name)
                if not isDeco then break end
            end

            if metadata.songName == "Tutorial" then
                isDeco = false
            end

            -- if isDeco then
            --     print(metadata.songName)
            -- end
        end
    end
end
'''
match_indent = true